// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PaginatedInvoices struct {
	Data  []*Invoice `json:"data"`
	Total int        `json:"total"`
}

type CreateInvoice struct {
	DateCreated int     `json:"dateCreated"`
	From        string  `json:"from"`
	Address     string  `json:"address"`
	Amount      float64 `json:"amount"`
}

type Invoice struct {
	ID          string  `json:"_id" bson:"_id"`
	DateCreated int     `json:"dateCreated"`
	From        string  `json:"from"`
	Address     string  `json:"address"`
	Amount      float64 `json:"amount"`
}