// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangePassword struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginReturn struct {
	User  *User  `json:"user"`
	Token string `json:"token"`
}

type UpdateInvoice struct {
	ID          string  `json:"id"`
	DateCreated int     `json:"DateCreated"`
	From        string  `json:"From"`
	Address     string  `json:"Address"`
	Amount      float64 `json:"Amount"`
}

type UpdateUser struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

type VerifyToken struct {
	Token string `json:"token"`
}
