// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type User struct {
	ID       string `json:"_id" bson:"_id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type CreateOwner struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Key      string `json:"key"`
}

type CreateUser struct {
	Email    string `json:"email"`
	Role     string `json:"role"`
	Password string `json:"password"`
}

type Role string

const (
	RoleOwner Role = "OWNER"
	RoleAcct  Role = "ACCT"
)

var AllRole = []Role{
	RoleOwner,
	RoleAcct,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleOwner, RoleAcct:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
