name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prune dangling images
      run: docker image prune -f
    - name: Checker
      run: ls && pwd
    - name: Build docker compose
      run: docker-compose up --detach
    - name: Restart nginx
      run: sudo systemctl restart nginx
